use_frameworks!

platform :ios, '8.0'

target 'AcmeListKit_Example' do
  pod 'AcmeListKit', :path => '../'

  target 'AcmeListKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
